version: 2 # use CircleCI 2.0

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  
  build-deploy:
    jobs:
      - build
jobs:
  build: 
    working_directory: ~/EricHarvey/geometry
    docker:
      - image: crystallang/crystal
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run:
          name: test
          command: crystal spec
